name: Code quality

on:
  push:
    branches-ignore:
      - 'temp/**'
      - 'backup/**'
      - 'changeset-release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DO_NOT_TRACK: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: yarn
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Check prettier styles
        run: yarn stylecheck

      - name: Test
        run: yarn test:cover

      - name: Update badges
        uses: gaelgirodon/ci-badges-action@80d40916d70425ec3e712402231bf2ecd0ed7384
        with:
          gist-id: ${{ secrets.GIST_ID }}
          token: ${{ secrets.GIST_TOKEN }}
